const Products = [
  {
    id: "pencil",
    name: " Charcoal Pencils",
    mrp: "400",
    price: "295",
    color: "black",
    material: "Charcoal",
    images: {
      img2: "../../../src/assets/Images/c++.jpg",
      img1: "https://m.media-amazon.com/images/I/51JgRFkpXvL._SY450_.jpg",
      img3: "https://m.media-amazon.com/images/I/51TCCrsNJwL._SY450_.jpg",
      img4: "https://m.media-amazon.com/images/I/61AAPN3aWnL._SY606_.jpg",
    },
    currency: "₹",
  },
  {
    id: "C++book",
    name: "C++ Programming Book",
    price: "900",
    mrp: "1000",
    material: "paper",
    color: "white",
    images: {
      img1: "../../../src/assets/Images/c++.jpg",
      img2: "https://m.media-amazon.com/images/I/51YOC-rGabL.jpg",
      img3: "https://m.media-amazon.com/images/I/71QEiC6i6WL.jpg",
      img4: "https://m.media-amazon.com/images/I/5197qo6Q1GL._SX418_BO1,204,203,200_.jpg",
    },
    currency: "₹",
  },
  {
    id: "pythonbook",
    name: "Python Book",
    price: "1199",
    mrp: "1500",
    material: "paper",
    color: "white",
    images: {
      img1:"../../../src/assets/Images/python.jpg",
      img5: "https://m.media-amazon.com/images/I/51PzX0ZSULL.jpg",
      img2: "https://m.media-amazon.com/images/I/61K0QVReUML.jpg",
      img3: "https://m.media-amazon.com/images/I/71pd1VdGjFL._AC_SY75_CR,0,0,75,75_.jpg",
      img4: "https://m.media-amazon.com/images/I/71pd1VdGjFL._AC_SY75_CR,0,0,75,75_.jpg",
    },
    currency: "₹",
  },
  {
    id: "javabook",
    name: "Java Programming Book",
    price: "1499",
    mrp: "1999",
    material: "paper",
    color: "white",
    images: {
      img1: "../../../src/assets/Images/java.jpg",
      img2: "https://m.media-amazon.com/images/I/71dD7+HV9yL.jpg",
      img3: "https://m.media-amazon.com/images/I/61F-wMUQ5ML.jpg",
      img4: "https://m.media-amazon.com/images/I/71dD7+HV9yL.jpg",
    },
    currency: "₹",
  },
  {
    id: "sqlbook",
    name: "SQL Book",
    price: "799",
    mrp: "1599",
    material: "paper",
    color: "white",
    images: {
      img1: "../../../src/assets/Images/mysql.jpg",
      img2: "https://m.media-amazon.com/images/I/514znqvCRKL.jpg",
      img3: "https://m.media-amazon.com/images/I/61Un90t-JxL.jpg",
      img4: "https://m.media-amazon.com/images/I/514znqvCRKL.jpg",
    },
    currency: "₹",
  },
  {
    id: "reactbook",
    name: "React Project ",
    price: "555",
    mrp: "999",
    material: "paper",
    color: "white",
    images: {
      img1: "../../../src/assets/Images/react.jpg",
      img2: "https://m.media-amazon.com/images/I/71p5VH4lUvL._AC_SX75_CR,0,0,75,75_.jpg",
      img3: "https://m.media-amazon.com/images/I/71uHpFe9W4L.jpg",
      img4: "https://m.media-amazon.com/images/I/71p5VH4lUvL._AC_SX75_CR,0,0,75,75_.jpg",
    },
    currency: "₹",
  },
  {
    id: "Appleipad",
    name: " Apple iPad Pro",
    price: "99999",
    mrp: "122900",
    material: "electronics",
    color: "Grey",
    images: {
      img1: "https://m.media-amazon.com/images/I/71brAk7Sc2L._SL1500_.jpg",
      img2: "https://m.media-amazon.com/images/I/81c+9BOQNWL._SL1500_.jpg",
      img3: "https://m.media-amazon.com/images/I/91qLD9hZWkL._SL1500_.jpg",
      img4: "https://m.media-amazon.com/images/I/71IXi+dxjHL._SL1500_.jpg",
    },
    currency: "₹",
  },
  {
    id: "asuslaptop",
    name: "ASUS ROG Flow X16 ",
    price: "211990",
    mrp: "254990",
    material: "electronics",
    color: "black",
    images: {
      img1: "https://m.media-amazon.com/images/I/718uAeMuzlL._SY450_.jpg",
      img2: "https://m.media-amazon.com/images/I/81eMwKSY2GL._SY450_.jpg",
      img3: "https://m.media-amazon.com/images/I/71NRHF3mQHL._SY450_.jpg",
      img4: "https://m.media-amazon.com/images/I/713mEsxz8AL._SY450_.jpg",
    },
    currency: "₹",
  },
  {
    id: "lgmonitor",
    name: "LG Ultragear ",
    price: "50199",
    mrp: "75000",
    material: "electronics",
    color: "black",
    images: {
      img1: "../../../src/assets/Images/monitor.jpg",
      img2: "https://m.media-amazon.com/images/I/61bk0zP76zL._SX679_.jpg",
      img3: "https://m.media-amazon.com/images/I/61SeJuNGiHL._SX679_.jpg",
      img4: "https://m.media-amazon.com/images/I/71uUA2tb2iL._SX679_.jpg",
    },
    currency: "₹",
  },
];

export default Products;
